### ISSUE TITLE
Errors when running npm-start

### ISSUE THREAD

**Issue by marianatuma** [auth0-blog/angular2-routing#2]
I just cloned the repo, installed it and ran `npm-start`, and got the following errors:

```

ERROR in ./src/main.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/home/marianaeficid/Documents/Eficid/angular2-routing/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/home/marianaeficid/Documents/Eficid/angular2-routing/node_modules/tslint/lib/tslint.js:26:44)
    at Object.lint (/home/marianaeficid/Documents/Eficid/angular2-routing/node_modules/tslint-loader/index.js:63:23)
    at Object.module.exports (/home/marianaeficid/Documents/Eficid/angular2-routing/node_modules/tslint-loader/index.js:151:8)

ERROR in ./src/vendor.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/home/marianaeficid/Documents/Eficid/angular2-routing/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/home/marianaeficid/Documents/Eficid/angular2-routing/node_modules/tslint/lib/tslint.js:26:44)
    at Object.lint (/home/marianaeficid/Documents/Eficid/angular2-routing/node_modules/tslint-loader/index.js:63:23)
    at Object.module.exports (/home/marianaeficid/Documents/Eficid/angular2-routing/node_modules/tslint-loader/index.js:151:8)
```

I can still access localhost:3000, but the angular2 app doesn't load.

**Comment by chenkie** [comment]
Likely a dependency version issue. I'll take a look and update the deps :)
